name: ci

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest

    env:
      TZ: Asia/Tokyo

    steps:
      - name: Checkout 🛎
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4

      - name: Setup node env 🏗
        uses: actions/setup-node@v4
        with:
          node-version-file: '.node-version'
          cache: 'pnpm'

      - name: Install dependencies 👨🏻‍💻
        run: pnpm install --frozen-lockfile

      - name: Run ESLint
        run: pnpm lint

      - name: Run Tests for Browser environment
        run: pnpm test:browser --run

      - name: Run Tests for Node.js environment
        run: pnpm test:node --run

      - name: Run build
        run: pnpm build
